# Copyright 2018, Naomi Paulmin

# [START gae_quickstart_yaml]
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /
  static_dir: dist
# [END gae_quickstart_yaml]
